/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FacultySetupRouteImport } from './routes/_faculty.setup'
import { Route as FacultySentimentRouteImport } from './routes/_faculty.sentiment'
import { Route as FacultyJdTrackerRouteImport } from './routes/_faculty.jd-tracker'
import { Route as FacultyDashboardRouteImport } from './routes/_faculty.dashboard'
import { Route as FacultyAlertsRouteImport } from './routes/_faculty.alerts'
import { Route as FacultyActivityRouteImport } from './routes/_faculty.activity'

const FacultySetupRoute = FacultySetupRouteImport.update({
  id: '/_faculty/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySentimentRoute = FacultySentimentRouteImport.update({
  id: '/_faculty/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyJdTrackerRoute = FacultyJdTrackerRouteImport.update({
  id: '/_faculty/jd-tracker',
  path: '/jd-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/_faculty/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyAlertsRoute = FacultyAlertsRouteImport.update({
  id: '/_faculty/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyActivityRoute = FacultyActivityRouteImport.update({
  id: '/_faculty/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/activity': typeof FacultyActivityRoute
  '/alerts': typeof FacultyAlertsRoute
  '/dashboard': typeof FacultyDashboardRoute
  '/jd-tracker': typeof FacultyJdTrackerRoute
  '/sentiment': typeof FacultySentimentRoute
  '/setup': typeof FacultySetupRoute
}
export interface FileRoutesByTo {
  '/activity': typeof FacultyActivityRoute
  '/alerts': typeof FacultyAlertsRoute
  '/dashboard': typeof FacultyDashboardRoute
  '/jd-tracker': typeof FacultyJdTrackerRoute
  '/sentiment': typeof FacultySentimentRoute
  '/setup': typeof FacultySetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_faculty/activity': typeof FacultyActivityRoute
  '/_faculty/alerts': typeof FacultyAlertsRoute
  '/_faculty/dashboard': typeof FacultyDashboardRoute
  '/_faculty/jd-tracker': typeof FacultyJdTrackerRoute
  '/_faculty/sentiment': typeof FacultySentimentRoute
  '/_faculty/setup': typeof FacultySetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/activity'
    | '/alerts'
    | '/dashboard'
    | '/jd-tracker'
    | '/sentiment'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/alerts'
    | '/dashboard'
    | '/jd-tracker'
    | '/sentiment'
    | '/setup'
  id:
    | '__root__'
    | '/_faculty/activity'
    | '/_faculty/alerts'
    | '/_faculty/dashboard'
    | '/_faculty/jd-tracker'
    | '/_faculty/sentiment'
    | '/_faculty/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FacultyActivityRoute: typeof FacultyActivityRoute
  FacultyAlertsRoute: typeof FacultyAlertsRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyJdTrackerRoute: typeof FacultyJdTrackerRoute
  FacultySentimentRoute: typeof FacultySentimentRoute
  FacultySetupRoute: typeof FacultySetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_faculty/setup': {
      id: '/_faculty/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof FacultySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/sentiment': {
      id: '/_faculty/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof FacultySentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/jd-tracker': {
      id: '/_faculty/jd-tracker'
      path: '/jd-tracker'
      fullPath: '/jd-tracker'
      preLoaderRoute: typeof FacultyJdTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/dashboard': {
      id: '/_faculty/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/alerts': {
      id: '/_faculty/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof FacultyAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/activity': {
      id: '/_faculty/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof FacultyActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FacultyActivityRoute: FacultyActivityRoute,
  FacultyAlertsRoute: FacultyAlertsRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyJdTrackerRoute: FacultyJdTrackerRoute,
  FacultySentimentRoute: FacultySentimentRoute,
  FacultySetupRoute: FacultySetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
